version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: gunicorn main:app --bind 0.0.0.0:8081 --timeout 360
    depends_on:
      - db
    networks:
      - tg-app-network

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - tg-app-network

networks:
  tg-app-network: